<a href="https://colab.research.google.com/github/kdlogan19/CAP6610/blob/master/Homework2_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
df = pd.read_csv("ionosphere.data",header = None)

In [5]:
df

0   1        2        3        4   ...       30       31       32       33  34
0     1   0  0.99539 -0.05889  0.85243  ...  0.42267 -0.54487  0.18641 -0.45300   g
1     1   0  1.00000 -0.18829  0.93035  ... -0.16626 -0.06288 -0.13738 -0.02447   b
2     1   0  1.00000 -0.03365  1.00000  ...  0.60436 -0.24180  0.56045 -0.38238   g
3     1   0  1.00000 -0.45161  1.00000  ...  0.25682  1.00000 -0.32382  1.00000   b
4     1   0  1.00000 -0.02401  0.94140  ... -0.05707 -0.59573 -0.04608 -0.65697   g
..   ..  ..      ...      ...      ...  ...      ...      ...      ...      ...  ..
346   1   0  0.83508  0.08298  0.73739  ...  0.86660 -0.10714  0.90546 -0.04307   g
347   1   0  0.95113  0.00419  0.95183  ...  0.94066 -0.00035  0.91483  0.04712   g
348   1   0  0.94701 -0.00034  0.93207  ...  0.92459  0.00442  0.92697 -0.00577   g
349   1   0  0.90608 -0.01657  0.98122  ...  0.96022 -0.03757  0.87403 -0.16243   g
350   1   0  0.84710  0.13533  0.73638  ...  0.75747 -0.06678  0.85764 -0.06151   g

[351 rows x 35 columns]

In [66]:
df_train = df.iloc[:300,:34]
df_test = df.iloc[300:,:34]
df_test.shape

(51, 34)

In [0]:
y_train = df.iloc[:300,34]

In [68]:
y_train

0      1
1      1
2      1
3      1
4      1
      ..
295    1
296    1
297    1
298    1
299    1
Name: 34, Length: 300, dtype: object

In [0]:
for i in range(len(y_train)):
  if y_train[i] =='g':
    y_train[i] = 0
  else:
    y_train[i] = 1

In [70]:
y_train

0      1
1      1
2      1
3      1
4      1
      ..
295    1
296    1
297    1
298    1
299    1
Name: 34, Length: 300, dtype: object

In [71]:
y_test = df.iloc[300:,34]
y_test.shape

(51,)

In [0]:
for j in range(300, 300+len(y_test)):
  if y_test[j] == 'g':
    y_test[j] = 0
  else:
    y_test[j] = 1

In [73]:
df_train.shape

(300, 34)

In [0]:
df_train = df_train.to_numpy()
df_test = df_test.to_numpy()
y_train = y_train.to_numpy().reshape(300,1)
y_test =  y_test.to_numpy().reshape(51,1)


In [0]:
import numpy as np
ones = np.ones((300,1))

In [0]:
X_train = np.block([ones,df_train])

In [80]:
X_train.shape

(300, 35)

In [0]:
thetha =  np.matmul(np.linalg.pinv(X_train),y_train)

In [81]:
thetha.shape

(35, 1)

In [0]:
X_test = np.block([np.ones(shape = (51,1), dtype= int),df_test])

In [86]:
X_test.shape

(51, 35)

In [113]:
y_pred = np.matmul(X_test,thetha)
y_pred

array([[0.9999999999999974],
       [0.9999999999999974],
       [0.9999999999999946],
       [0.9999999999999948],
       [0.9999999999999944],
       [0.9999999999999958],
       [0.9999999999999963],
       [0.9999999999999967],
       [0.999999999999997],
       [0.9999999999999976],
       [0.9999999999999974],
       [0.9999999999999979],
       [0.9999999999999946],
       [0.9999999999999952],
       [0.9999999999999972],
       [0.9999999999999977],
       [0.9999999999999977],
       [0.9999999999999948],
       [0.9999999999999951],
       [0.9999999999999949],
       [0.9999999999999944],
       [0.9999999999999948],
       [0.9999999999999947],
       [0.9999999999999966],
       [0.9999999999999974],
       [0.9999999999999976],
       [0.9999999999999976],
       [0.9999999999999981],
       [0.9999999999999972],
       [0.9999999999999948],
       [0.9999999999999949],
       [0.9999999999999948],
       [0.9999999999999949],
       [0.9999999999999946],
       [0.99999

In [0]:
y_pred = y_pred.astype(float)

In [110]:
y_pred.round()

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [115]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_pred)

3.970679993953501e-15



---



---




#                 HINGE LOSS







In [0]:
import cvxpy as cp
w = cp.Variable((34,1))
b = cp.Variable()

In [0]:
loss_train = cp.sum(cp.pos(1- (df_train@w + b - y_train)))

In [138]:
loss_train

Expression(CONVEX, NONNEGATIVE, ())

In [139]:
cp.Problem(cp.Minimize(loss_train),[]).solve(solver = cp.ECOS)

-1.4381013516006974e-12

In [140]:
w.value

array([[ 6.91520377e-06],
       [ 0.00000000e+00],
       [ 1.38167789e-06],
       [-4.32240827e-10],
       [ 1.36551660e-06],
       [ 3.78371060e-07],
       [ 1.72852136e-06],
       [ 8.70376966e-07],
       [ 1.45342901e-06],
       [ 1.51145799e-06],
       [ 1.59691303e-06],
       [ 3.33622253e-07],
       [ 7.78874714e-07],
       [-1.36730579e-07],
       [-1.41947741e-08],
       [ 1.39037173e-07],
       [ 4.89928909e-07],
       [-2.33670709e-07],
       [ 1.14659898e-07],
       [-9.42730629e-08],
       [ 7.50811947e-08],
       [ 5.30902107e-07],
       [ 1.72505478e-07],
       [-1.91258318e-07],
       [ 1.05623224e-06],
       [-4.98469108e-07],
       [ 3.49935821e-06],
       [-9.10112027e-07],
       [-1.87662773e-07],
       [-1.33988939e-08],
       [ 1.33956762e-07],
       [ 2.81707848e-07],
       [-1.70632503e-07],
       [ 1.13695824e-08]])

In [143]:
b.value

array(2.54836293)

In [0]:
y_pred = df_test@w + b

In [146]:
y_pred.value

array([[2.54837416],
       [2.54837413],
       [2.54838308],
       [2.54838257],
       [2.54838279],
       [2.54837744],
       [2.54837619],
       [2.54837126],
       [2.54837208],
       [2.54837429],
       [2.54837468],
       [2.54837452],
       [2.54838321],
       [2.54838104],
       [2.54837424],
       [2.54837483],
       [2.54837605],
       [2.54838191],
       [2.54837962],
       [2.5483819 ],
       [2.54838332],
       [2.54838207],
       [2.54838255],
       [2.54837642],
       [2.54837504],
       [2.5483754 ],
       [2.54837656],
       [2.54837608],
       [2.54837557],
       [2.54838224],
       [2.54838152],
       [2.54838112],
       [2.54838157],
       [2.54838305],
       [2.54838317],
       [2.54838328],
       [2.54837531],
       [2.54837665],
       [2.54837327],
       [2.54837494],
       [2.54836907],
       [2.5483829 ],
       [2.54838044],
       [2.54837682],
       [2.54838058],
       [2.54837913],
       [2.54838116],
       [2.548

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]], dtype=object)