<a href="https://colab.research.google.com/github/kdlogan19/CAP6610/blob/master/HW2_4_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



---


# Lease Square Loss



---



In [0]:
import pandas as pd

data = pd.read_csv("winequality-red.csv", sep = ';')

In [0]:
wine_train = data.iloc[:1400,:11]
wine_test = data.iloc[1400:,:11]

In [0]:
y_train = data.iloc[:1400,11]
y_test = data.iloc[1400:,11]

In [6]:
import numpy as np
ones = np.ones((1400,1))
ones
ones.shape

(1400, 1)

In [7]:
A = np.block([[ones, wine_train]])
A

array([[ 1.  ,  7.4 ,  0.7 , ...,  3.51,  0.56,  9.4 ],
       [ 1.  ,  7.8 ,  0.88, ...,  3.2 ,  0.68,  9.8 ],
       [ 1.  ,  7.8 ,  0.76, ...,  3.26,  0.65,  9.8 ],
       ...,
       [ 1.  ,  7.3 ,  0.59, ...,  3.28,  0.52,  9.9 ],
       [ 1.  ,  7.  ,  0.6 , ...,  3.52,  0.62, 10.2 ],
       [ 1.  ,  7.2 ,  0.67, ...,  3.42,  0.72, 11.1 ]])

In [8]:
A.shape


(1400, 12)

In [9]:
type(y_train)

pandas.core.series.Series

In [0]:
y_train = y_train.to_numpy()

In [0]:
y_train = y_train.reshape(1400,1)

In [12]:
y_train.shape

(1400, 1)

In [0]:
res = np.matmul(np.linalg.pinv(A),y_train)

In [0]:
A_test = np.block([np.ones((199,1)),wine_test])

In [16]:
A_test.shape

(199, 12)

In [0]:
y_test = y_test.to_numpy()

In [0]:
y_test.reshape(199,1)
result = np.matmul(A_test,res)

In [0]:
result = np.round(result)

In [20]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,result)

0.4371859296482412







---


# *********************HUBER LOSS FUNCTION***************************************** 



---





In [0]:
wine_train
wine_train = wine_train.to_numpy()


In [0]:
import cvxpy as cp
w = cp.Variable((11,1)); b = cp.Variable()

In [0]:
obj_train = cp.sum(cp.huber(wine_train@w + b - y_train))

In [28]:
cp.Problem(cp.Minimize(obj_train), []).solve()

535.4177751956599

In [30]:
w.value

array([[ 5.01133982e-02],
       [-1.03205164e+00],
       [-1.83368522e-01],
       [ 2.37555652e-02],
       [-1.53504304e+00],
       [ 3.13824283e-03],
       [-3.42146282e-03],
       [-3.46798683e+01],
       [-1.00830934e-01],
       [ 8.91948016e-01],
       [ 2.63729352e-01]])

In [31]:
b.value

array(37.58293877)

In [0]:
wine_test = wine_test.to_numpy()
y_test = y_test.reshape(199,1)

In [0]:
obj_test = wine_test@w + b

In [34]:
obj_test.shape

(199, 1)

In [35]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,obj_test.value)

0.5327156477588904



---



---


# **       *********** HINGE LOSS******************    **

---



In [0]:
wine_train = wine_train.to_numpy()
y_train = y_train.to_numpy()
y_train = y_train.reshape(1400,1)
wine_test = wine_test.to_numpy()
y_test = y_test.to_numpy()
y_test = y_test.reshape(199,1)


In [0]:
w2 = cp.Variable((11,1))
b2 = cp.Variable()

In [0]:
loss_train = cp.sum(cp.max(cp.abs(wine_train@w2 + b2 - y_train) - 0.5))

In [40]:
loss_train

Expression(CONVEX, UNKNOWN, ())

In [41]:
cp.Problem(cp.Minimize(loss_train),[]).solve(solver = cp.ECOS)

1.4427196879472994

In [42]:
w2.value

array([[-1.02443588e-01],
       [-1.14031934e+00],
       [-8.03873920e-01],
       [-1.02267158e-01],
       [-2.19223559e+00],
       [-6.56619772e-03],
       [ 2.54697174e-04],
       [ 3.58110026e+01],
       [-2.66588926e+00],
       [ 4.24335853e-01],
       [ 3.75420175e-01]])

In [43]:
b2.value

array(-23.29192227)

In [0]:
hinge_pred = wine_test@w2 + b2

In [45]:
print(type(hinge_pred.value))
type(y_test)

<class 'numpy.ndarray'>


numpy.ndarray

In [46]:
mean_absolute_error(y_test,hinge_pred.value)

0.5948590304113915